### ISSUE TITLE
Cache Busting with Sites

### ISSUE THREAD

**Issue by zmetcalf** [craftcms/element-api#79] opened 2018-07-02 20:05 UTC
We have an instance that is using the multi-sites system, and we are using the caching that was just implemented. (Thank you!) However, we are finding that the cache is not busting on update of elements. Is there an update to this plugin's codebase that can be made, do we need to bust the cache with a custom event within a plugin, or something else?

**Comment by brandonkelly** [comment] 2018-07-29 13:06
Duplicate of #47

**Closed by brandonkelly** 2018-07-29 13:06 UTC

**Comment by roberttolton** [comment] 2018-09-04 03:40
Was this resolved? #47 has also been closed.

**Comment by zmetcalf** [comment] 2018-09-04 13:36
I ended up just writing the Craft 3 version of this:
```
craft()->on('elements.onSaveElement', function(Event $event) {
          craft()->cache->flush();
});
```
I don't think they are interested in doing much more than this.

**Comment by jorisnoo** [comment] 2020-10-29 07:50
@zmetcalf May I ask what you ended up using for Craft 3?

**Comment by zmetcalf** [comment] 2020-10-29 19:07
Been a long, long time since I did this, but if you are looking for something simple, just create a basic plugin and add that line in the main plugin file. I think the big drawback of this is that it resets cache for everything. You'd need to figure out their cache key system to make it better.
