### ISSUE TITLE
When using select the api breaks because of output being transmitted to early

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/element-api#125] opened 2020-04-02 06:34 UTC
PHP Warning 'yii\base\ErrorException' with message 'Header may not contain more than a single header, new line detected' 

in /Users/lenvanessen/Sites/early-games/vendor/yiisoft/yii2/web/Response.php:380

```
Stack trace:
#0 /Users/lenvanessen/Sites/early-games/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(2, 'Header may not ...', '/Users/lenvanes...', 380)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'Header may not ...', '/Users/lenvanes...', 380, Array)
#2 /Users/lenvanessen/Sites/early-games/vendor/yiisoft/yii2/web/Response.php(380): header('HTTP/1.1 404 SQ...')
#3 /Users/lenvanessen/Sites/early-games/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#4 /Users/lenvanessen/Sites/early-games/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Response->send()
#5 /Users/lenvanessen/Sites/early-games/web/index.php(26): yii\base\Application->run()
#6 /Users/lenvanessen/.composer/vendor/laravel/valet/server.php(158): require('/Users/lenvanes...')
#7 {main}
```

**Comment by brandonkelly** [comment] 2021-08-31 16:58
This looks like a duplicate of #115, but I’m not sure how to reproduce it.

**Closed by brandonkelly** 2021-08-31 16:58 UTC

**Comment by brandonkelly** [comment] 2021-09-01 03:15
In the case of #138, this ended up being an issue with PHP 7.3.
